# Generated by Django 3.1.5 on 2021-01-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the events host.', max_length=20, unique=True)),
                ('weblink', models.URLField(blank=True, help_text='URL to host info.', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event type.', max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event.', max_length=30)),
                ('date', models.DateField(help_text='Date of the event.')),
                ('time', models.TimeField(help_text='Time of the event.')),
                ('location', models.CharField(default='TBA', help_text='Location for the event.', max_length=30)),
                ('weblink', models.URLField(blank=True, help_text='URL to event info.', null=True)),
                ('event_host', models.ForeignKey(blank=True, help_text='Type of event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventhost')),
                ('event_type', models.ForeignKey(blank=True, help_text='Type of event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventtype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
