# Generated by Django 3.1.5 on 2021-01-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_local',
            field=models.BooleanField(default=True, help_text='Is this a local event?'),
        ),
    ]
