# Generated by Django 3.1.5 on 2021-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='Ending time of the event.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='Starting time of the event.', null=True),
        ),
    ]
